# Generated by Django 5.2.6 on 2025-09-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ayakkabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_adi', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(unique=True)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.marka')),
            ],
        ),
        migrations.CreateModel(
            name='AyakkabiVaryant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renk', models.CharField(max_length=50)),
                ('beden', models.CharField(max_length=10)),
                ('stok', models.IntegerField(default=0)),
                ('ayakkabi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.ayakkabi')),
            ],
            options={
                'unique_together': {('ayakkabi', 'renk', 'beden')},
            },
        ),
    ]
