# Generated by Django 5.2.6 on 2025-09-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayakkabi',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
