# Generated by Django 5.2.6 on 2025-09-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_alter_ayakkabi_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('sepet_id', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SepetOgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(default=1)),
                ('sepet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.sepet')),
                ('varyant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.ayakkabivaryant')),
            ],
            options={
                'unique_together': {('sepet', 'varyant')},
            },
        ),
    ]
