# Generated by Django 5.2.6 on 2025-09-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_sepet_sepetogesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepet_id', models.CharField(blank=True, max_length=250)),
                ('ad_soyad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(max_length=250)),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('durum', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Kargoda', 'Kargoda'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='Beklemede', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.AlterModelOptions(
            name='ayakkabi',
            options={'verbose_name': 'Ayakkabı', 'verbose_name_plural': 'Ayakkabılar'},
        ),
        migrations.AlterModelOptions(
            name='ayakkabivaryant',
            options={'verbose_name': 'Ayakkabı Varyantı', 'verbose_name_plural': 'Ayakkabı Varyantları'},
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='sepet',
            options={'ordering': ['tarih'], 'verbose_name': 'Sepet', 'verbose_name_plural': 'Sepetler'},
        ),
        migrations.AlterModelOptions(
            name='sepetogesi',
            options={'verbose_name': 'Sepet Öğesi', 'verbose_name_plural': 'Sepet Öğeleri'},
        ),
        migrations.RenameField(
            model_name='sepet',
            old_name='olusturma_tarihi',
            new_name='tarih',
        ),
        migrations.AlterUniqueTogether(
            name='sepetogesi',
            unique_together={('varyant', 'sepet')},
        ),
        migrations.AddField(
            model_name='sepetogesi',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ayakkabi',
            name='model_adi',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ayakkabi',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sepet',
            name='sepet_id',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='sepetogesi',
            name='miktar',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='sepet',
            table='sepet',
        ),
        migrations.AlterModelTable(
            name='sepetogesi',
            table='sepet_ogeleri',
        ),
        migrations.CreateModel(
            name='SiparisOgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(default=1)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogeler', to='katalog.siparis')),
                ('varyant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.ayakkabivaryant')),
            ],
            options={
                'verbose_name': 'Sipariş Öğesi',
                'verbose_name_plural': 'Sipariş Öğeleri',
            },
        ),
    ]
