# Generated by Django 5.2.6 on 2025-09-29 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0004_siparis_alter_ayakkabi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayakkabi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ayakkabivaryant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sepet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sepetogesi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='siparis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='siparisogesi',
            options={},
        ),
        migrations.RenameField(
            model_name='sepet',
            old_name='tarih',
            new_name='eklenme_tarihi',
        ),
        migrations.AlterUniqueTogether(
            name='ayakkabivaryant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sepetogesi',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ayakkabi',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='ayakkabi_resimleri/', verbose_name='Ürün Resmi'),
        ),
        migrations.AlterField(
            model_name='ayakkabi',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ayakkabi',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='sepet',
            name='sepet_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='sepetogesi',
            name='miktar',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='adres',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('Hazırlanıyor', 'Hazırlanıyor'), ('Kargoda', 'Kargoda'), ('Teslim Edildi', 'Teslim Edildi'), ('İptal Edildi', 'İptal Edildi')], default='Hazırlanıyor', max_length=20),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='sepet_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Anonim Sepet ID'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='toplam_fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='siparisogesi',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı'),
        ),
        migrations.AlterField(
            model_name='siparisogesi',
            name='miktar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siparisogesi',
            name='siparis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.siparis'),
        ),
        migrations.AlterModelTable(
            name='sepet',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sepetogesi',
            table=None,
        ),
        migrations.RemoveField(
            model_name='sepetogesi',
            name='aktif',
        ),
    ]
